baseURL: "https://timmyisnotfat.github.io/" 
title: Yihao Huang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: blog/
          weight: 6

params:
    description: "This website hosts Yihao Huang's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Yihao Huang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yihao Huang
          subtitle: "I am Yihao Huang. This website hosts my research papers, books, course materials, data, curriculum vitae, and contact information."
          imageUrl: "yihao_profile_pic.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:yh26e@fsu.edu
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/timmyisnotfat
        - name: Substack
          url: https://user.substack.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yihao Huang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
